name: Build container and validate lint/tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint-validation:
    name: Validate Go code linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
  checkout-code-and-validate:
    needs: lint-validation
    name: Checkout code and validate tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build the stack
        run: docker network create your_network || true
      - name: Build the stack
        run: docker-compose -f docker-compose.yml.test up -d --build --force-recreate --remove-orphans
      - name: Test
        run: docker-compose -f docker-compose.yml.test exec -T souin go test -v -race ./...
  validate-prod-container-building:
    needs: checkout-code-and-validate
    name: Validate that the container build for prod
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Build the stack
        run: docker network create your_network || true
      -
        name: Build the stack
        run: docker-compose -f docker-compose.yml.prod up -d --build --force-recreate --remove-orphans
      -
        name: Souin container healthceck
        run: docker-compose -f docker-compose.yml.prod exec -T souin ls
