name: Build container and validate lint/tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint-validation:
    name: Validate Go code linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
  unit-test-golang:
    needs: lint-validation
    name: Checkout code and validate tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build the stack
        run: docker network create your_network || true
      - name: Build the stack
        run: docker-compose -f docker-compose.yml.test up -d --build --force-recreate --remove-orphans
      - name: Test
        run: go test -v -race $(go list ./... | grep -v cache/providers)
  unit-test-golang-with-services:
    needs: lint-validation
    name: Checkout code and validate tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build the stack
        run: docker network create your_network || true
      - name: Build the stack
        run: docker-compose -f docker-compose.yml.test up -d --build --force-recreate --remove-orphans
      - name: Test
        # disabled race to pass the EmbeddedOlric test
        run: docker-compose -f docker-compose.yml.test exec -T souin go test -v cache/providers
  validate-prod-container-building:
    needs: unit-test-golang-with-services
    name: Validate that the container build for prod
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Build the stack
        run: docker network create your_network || true
      -
        name: Build the stack
        run: docker-compose -f docker-compose.yml.prod up -d --build --force-recreate --remove-orphans
      -
        name: Souin container healthceck
        run: docker-compose -f docker-compose.yml.prod exec -T souin ls
