name: Build and validate Souin as plugins

on: [push]

jobs:
  build-caddy-validator:
    name: Check that Souin build as caddy module
    runs-on: ubuntu-latest
    steps:
      -
        name: Add domain.com host to /etc/hosts
        run: |
          sudo echo "127.0.0.1 domain.com" | sudo tee -a /etc/hosts
      -
        name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Install xcaddy
        run: |
          sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/xcaddy/gpg.key' | sudo apt-key add -
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/xcaddy/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-xcaddy.list
          sudo apt update
          sudo apt install xcaddy
      -
        name: Build Souin as caddy module
        run: cd plugins/caddy && xcaddy build --with github.com/darkweak/souin/plugins/caddy=./ --with github.com/darkweak/souin@latest=../..
      -
        name: Run detached caddy
        run: cd plugins/caddy && ./caddy run &
      -
        name: Run Caddy E2E tests
        uses: anthonyvscode/newman-action@v1
        with:
          collection: "docs/e2e/Souin E2E.postman_collection.json"
          folder: Caddy
          reporters: cli
          delayRequest: 5000
  build-tyk-validator:
    name: Check that Souin build as Tyk middleware
    runs-on: ubuntu-latest
    steps:
      -
        name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Build Souin as Tyk plugin
        run: make build-and-run-tyk
      -
        name: Wait for Souin is really loaded inside Tyk as middleware
        uses: jakejarvis/wait-action@master
        with:
          time: 30s
      -
        name: Set Tyk logs configuration result as environment variable
        run: cd plugins/tyk && echo "TYK_MIDDLEWARE_RESULT=$(docker-compose logs tyk-gateway | grep SouinResponseHandler)" >> $GITHUB_ENV
      -
        name: Check if the configuration is loaded to define if Souin is loaded too
        uses: nick-invision/assert-action@v1
        with:
          expected: 'level=info msg="Loaded Go response plugin: SouinResponseHandler" mwPath="/opt/tyk-gateway/middleware/souin-plugin.so" mwSymbolName=SouinResponseHandler'
          actual: ${{ env.TYK_MIDDLEWARE_RESULT }}
          comparison: contains
      -
        name: Run Tyk E2E tests
        uses: anthonyvscode/newman-action@v1
        with:
          collection: "docs/e2e/Souin E2E.postman_collection.json"
          folder: Tyk
          reporters: cli
          delayRequest: 5000
  build-traefik-validator:
    name: Check that Souin build as Træfik plugin
    runs-on: ubuntu-latest
    steps:
      -
        name: Add domain.com host to /etc/hosts
        run: |
          sudo echo "127.0.0.1 domain.com" | sudo tee -a /etc/hosts
      -
        name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Build Souin as Træfik plugin
        run: make build-and-run-traefik
      -
        name: Wait for Souin is really loaded inside Træfik as plugin
        uses: jakejarvis/wait-action@master
        with:
          time: 30s
      -
        name: Set traefik logs file result as environment variable
        run: cd plugins/traefik && echo "TRAEFIK_FILE_RESULT=$(docker-compose logs traefik | grep 'Starting provider \*file.Provider')" >> $GITHUB_ENV
      -
        name: Check logs to define if Souin configuration is loaded too
        uses: nick-invision/assert-action@v1
        with:
          expected: '/souin-configuration.yaml'
          actual: ${{ env.TRAEFIK_FILE_RESULT }}
          comparison: contains
      -
        name: Set traefik logs configuration result as environment variable
        run: cd plugins/traefik && echo "TRAEFIK_MIDDLEWARE_RESULT=$(docker-compose logs traefik | grep default_cache)" >> $GITHUB_ENV
      -
        name: Check if the configuration is loaded to define if Souin is loaded too
        uses: nick-invision/assert-action@v1
        with:
          expected: '"middlewares\":{\"souin\":{\"plugin\":{\"souin-plugin'
          actual: ${{ env.TRAEFIK_MIDDLEWARE_RESULT }}
          comparison: contains
      -
        name: Run Træfik E2E tests
        uses: anthonyvscode/newman-action@v1
        with:
          collection: "docs/e2e/Souin E2E.postman_collection.json"
          folder: Traefik
          reporters: cli
          delayRequest: 5000
