name: Build and validate Souin as plugins

on:
  - pull_request

jobs:
  build-caddy-validator:
    name: Check that Souin build as caddy module
    runs-on: ubuntu-latest
    steps:
      -
        name: Add domain.com host to /etc/hosts
        run: |
          sudo echo "127.0.0.1 domain.com" | sudo tee -a /etc/hosts
      -
        name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Install xcaddy
        run: |
          sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/xcaddy/gpg.key' | sudo apt-key add -
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/xcaddy/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-xcaddy.list
          sudo apt update
          sudo apt install xcaddy
      -
        name: Build Souin as caddy module
        run: cd plugins/caddy && xcaddy build --with github.com/darkweak/souin/plugins/caddy=./ --with github.com/darkweak/souin@latest=../..
      -
        name: Run detached caddy
        run: cd plugins/caddy && ./caddy run &
      -
        name: Run Caddy E2E tests
        uses: anthonyvscode/newman-action@v1
        with:
          collection: "docs/e2e/Souin E2E.postman_collection.json"
          folder: Caddy
          reporters: cli
          delayRequest: 5000
  build-echo-validator:
    name: Check that Souin build as Echo middleware
    runs-on: ubuntu-latest
    steps:
      -
        name: Add domain.com host to /etc/hosts
        run: |
          sudo echo "127.0.0.1 domain.com" | sudo tee -a /etc/hosts
      -
        name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Build Souin as Echo plugin
        run: make build-and-run-echo
      -
        name: Wait for Souin is really loaded inside Echo as middleware
        uses: jakejarvis/wait-action@master
        with:
          time: 30s
      -
        name: Set Echo logs configuration result as environment variable
        run: cd plugins/echo/examples && echo "ECHO_MIDDLEWARE_RESULT=$(docker-compose logs echo | grep Souin)" >> $GITHUB_ENV
      -
        name: Check if the configuration is loaded to define if Souin is loaded too
        uses: nick-invision/assert-action@v1
        with:
          expected: '"message":"Souin configuration is now loaded."'
          actual: ${{ env.ECHO_MIDDLEWARE_RESULT }}
          comparison: contains
      -
        name: Run Echo E2E tests
        uses: anthonyvscode/newman-action@v1
        with:
          collection: "docs/e2e/Souin E2E.postman_collection.json"
          folder: Echo
          reporters: cli
          delayRequest: 5000
  build-chi-validator:
    name: Check that Souin build as Chi middleware
    runs-on: ubuntu-latest
    steps:
      -
        name: Add domain.com host to /etc/hosts
        run: |
          sudo echo "127.0.0.1 domain.com" | sudo tee -a /etc/hosts
      -
        name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Build Souin as Chi plugin
        run: make build-and-run-chi
      -
        name: Wait for Souin is really loaded inside Chi as middleware
        uses: jakejarvis/wait-action@master
        with:
          time: 30s
      -
        name: Set Chi logs configuration result as environment variable
        run: cd plugins/chi/examples && echo "CHI_MIDDLEWARE_RESULT=$(docker-compose logs chi | grep Souin)" >> $GITHUB_ENV
      -
        name: Check if the configuration is loaded to define if Souin is loaded too
        uses: nick-invision/assert-action@v1
        with:
          expected: '"message":"Souin configuration is now loaded."'
          actual: ${{ env.CHI_MIDDLEWARE_RESULT }}
          comparison: contains
      -
        name: Run Chi E2E tests
        uses: anthonyvscode/newman-action@v1
        with:
          collection: "docs/e2e/Souin E2E.postman_collection.json"
          folder: Chi
          reporters: cli
          delayRequest: 5000
  build-fiber-validator:
    name: Check that Souin build as Fiber middleware
    runs-on: ubuntu-latest
    steps:
      -
        name: Add domain.com host to /etc/hosts
        run: |
          sudo echo "127.0.0.1 domain.com" | sudo tee -a /etc/hosts
      -
        name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Build Souin as Fiber plugin
        run: make build-and-run-fiber
      -
        name: Wait for Souin is really loaded inside Fiber as middleware
        uses: jakejarvis/wait-action@master
        with:
          time: 30s
      -
        name: Set Fiber logs configuration result as environment variable
        run: cd plugins/fiber/examples && echo "FIBER_MIDDLEWARE_RESULT=$(docker-compose logs fiber | grep Souin)" >> $GITHUB_ENV
      -
        name: Check if the configuration is loaded to define if Souin is loaded too
        uses: nick-invision/assert-action@v1
        with:
          expected: '"message":"Souin configuration is now loaded."'
          actual: ${{ env.FIBER_MIDDLEWARE_RESULT }}
          comparison: contains
      -
        name: Run Fiber E2E tests
        uses: anthonyvscode/newman-action@v1
        with:
          collection: "docs/e2e/Souin E2E.postman_collection.json"
          folder: Fiber
          reporters: cli
          delayRequest: 5000
  build-gin-validator:
    name: Check that Souin build as Gin middleware
    runs-on: ubuntu-latest
    steps:
      -
        name: Add domain.com host to /etc/hosts
        run: |
          sudo echo "127.0.0.1 domain.com" | sudo tee -a /etc/hosts
      -
        name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Build Souin as Gin plugin
        run: make build-and-run-gin
      -
        name: Wait for Souin is really loaded inside Gin as middleware
        uses: jakejarvis/wait-action@master
        with:
          time: 30s
      -
        name: Set Gin logs configuration result as environment variable
        run: cd plugins/gin/examples && echo "GIN_MIDDLEWARE_RESULT=$(docker-compose logs gin | grep Souin)" >> $GITHUB_ENV
      -
        name: Check if the configuration is loaded to define if Souin is loaded too
        uses: nick-invision/assert-action@v1
        with:
          expected: '"message":"Souin configuration is now loaded."'
          actual: ${{ env.GIN_MIDDLEWARE_RESULT }}
          comparison: contains
      -
        name: Run Gin E2E tests
        uses: anthonyvscode/newman-action@v1
        with:
          collection: "docs/e2e/Souin E2E.postman_collection.json"
          folder: Gin
          reporters: cli
          delayRequest: 5000
  build-goyave-validator:
    name: Check that Souin build as Goyave middleware
    runs-on: ubuntu-latest
    steps:
      -
        name: Add domain.com host to /etc/hosts
        run: |
          sudo echo "127.0.0.1 domain.com" | sudo tee -a /etc/hosts
      -
        name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Build Souin as Goyave plugin
        run: make build-and-run-goyave
      -
        name: Wait for Souin is really loaded inside Goyave as middleware
        uses: jakejarvis/wait-action@master
        with:
          time: 30s
      -
        name: Set Goyave logs configuration result as environment variable
        run: cd plugins/goyave/examples && echo "GOYAVE_MIDDLEWARE_RESULT=$(docker-compose logs goyave | grep Souin)" >> $GITHUB_ENV
      -
        name: Check if the configuration is loaded to define if Souin is loaded too
        uses: nick-invision/assert-action@v1
        with:
          expected: '"message":"Souin configuration is now loaded."'
          actual: ${{ env.GOYAVE_MIDDLEWARE_RESULT }}
          comparison: contains
      -
        name: Run Goyave E2E tests
        uses: anthonyvscode/newman-action@v1
        with:
          collection: "docs/e2e/Souin E2E.postman_collection.json"
          folder: Goyave
          reporters: cli
          delayRequest: 5000
  build-skipper-validator:
    name: Check that Souin build as Skipper middleware
    runs-on: ubuntu-latest
    steps:
      -
        name: Add domain.com host to /etc/hosts
        run: |
          sudo echo "127.0.0.1 domain.com" | sudo tee -a /etc/hosts
      -
        name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Build Souin as Skipper plugin
        run: make build-and-run-skipper
      -
        name: Wait for Souin is really loaded inside Skipper as middleware
        uses: jakejarvis/wait-action@master
        with:
          time: 40s
      -
        name: Set Skipper logs configuration result as environment variable
        run: cd plugins/skipper/examples && echo "SKIPPER_MIDDLEWARE_RESULT=$(docker-compose logs skipper | grep Souin)" >> $GITHUB_ENV
      -
        name: Check if the configuration is loaded to define if Souin is loaded too
        uses: nick-invision/assert-action@v1
        with:
          expected: '"message":"Souin configuration is now loaded."'
          actual: ${{ env.SKIPPER_MIDDLEWARE_RESULT }}
          comparison: contains
      -
        name: Run Skipper E2E tests
        uses: anthonyvscode/newman-action@v1
        with:
          collection: "docs/e2e/Souin E2E.postman_collection.json"
          folder: Skipper
          reporters: cli
          delayRequest: 5000
  build-souin-validator:
    name: Check that Souin build as Souin middleware
    runs-on: ubuntu-latest
    steps:
      -
        name: Add domain.com host to /etc/hosts
        run: |
          sudo echo "127.0.0.1 domain.com" | sudo tee -a /etc/hosts
      -
        name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Build Souin as Souin plugin
        run: make build-and-run-souin
      -
        name: Wait for Souin is really loaded inside Souin as middleware
        uses: jakejarvis/wait-action@master
        with:
          time: 40s
      -
        name: Set Souin logs configuration result as environment variable
        run: cd plugins/souin/examples && echo "SOUIN_MIDDLEWARE_RESULT=$(docker-compose logs souin | grep Souin)" >> $GITHUB_ENV
      -
        name: Check if the configuration is loaded to define if Souin is loaded too
        uses: nick-invision/assert-action@v1
        with:
          expected: '"message":"Souin configuration is now loaded."'
          actual: ${{ env.SOUIN_MIDDLEWARE_RESULT }}
          comparison: contains
      -
        name: Run Souin E2E tests
        uses: anthonyvscode/newman-action@v1
        with:
          collection: "docs/e2e/Souin E2E.postman_collection.json"
          folder: Souin
          reporters: cli
          delayRequest: 5000
  build-tyk-validator:
    name: Check that Souin build as Tyk middleware
    runs-on: ubuntu-latest
    steps:
      -
        name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Build Souin as Tyk plugin
        run: make build-and-run-tyk
      -
        name: Wait for Souin is really loaded inside Tyk as middleware
        uses: jakejarvis/wait-action@master
        with:
          time: 30s
      -
        name: Set Tyk logs configuration result as environment variable
        run: cd plugins/tyk && echo "TYK_MIDDLEWARE_RESULT=$(docker-compose logs tyk-gateway | grep SouinResponseHandler)" >> $GITHUB_ENV
      -
        name: Check if the configuration is loaded to define if Souin is loaded too
        uses: nick-invision/assert-action@v1
        with:
          expected: 'level=info msg="Loaded Go response plugin: SouinResponseHandler" mwPath="/opt/tyk-gateway/middleware/souin-plugin.so" mwSymbolName=SouinResponseHandler'
          actual: ${{ env.TYK_MIDDLEWARE_RESULT }}
          comparison: contains
      -
        name: Run Tyk E2E tests
        uses: anthonyvscode/newman-action@v1
        with:
          collection: "docs/e2e/Souin E2E.postman_collection.json"
          folder: Tyk
          reporters: cli
          delayRequest: 5000
  build-traefik-validator:
    name: Check that Souin build as Træfik plugin
    runs-on: ubuntu-latest
    steps:
      -
        name: Add domain.com host to /etc/hosts
        run: |
          sudo echo "127.0.0.1 domain.com" | sudo tee -a /etc/hosts
      -
        name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Build Souin as Træfik plugin
        run: make build-and-run-traefik
      -
        name: Wait for Souin is really loaded inside Træfik as plugin
        uses: jakejarvis/wait-action@master
        with:
          time: 30s
      -
        name: Set traefik logs file result as environment variable
        run: cd plugins/traefik && echo "TRAEFIK_FILE_RESULT=$(docker-compose logs traefik | grep 'Starting provider \*file.Provider')" >> $GITHUB_ENV
      -
        name: Check logs to define if Souin configuration is loaded too
        uses: nick-invision/assert-action@v1
        with:
          expected: '/souin-configuration.yaml'
          actual: ${{ env.TRAEFIK_FILE_RESULT }}
          comparison: contains
      -
        name: Set traefik logs configuration result as environment variable
        run: cd plugins/traefik && echo "TRAEFIK_MIDDLEWARE_RESULT=$(docker-compose logs traefik | grep default_cache)" >> $GITHUB_ENV
      -
        name: Check if the configuration is loaded to define if Souin is loaded too
        uses: nick-invision/assert-action@v1
        with:
          expected: '"middlewares\":{\"souin\":{\"plugin\":{\"souin-plugin'
          actual: ${{ env.TRAEFIK_MIDDLEWARE_RESULT }}
          comparison: contains
      -
        name: Run Træfik E2E tests
        uses: anthonyvscode/newman-action@v1
        with:
          collection: "docs/e2e/Souin E2E.postman_collection.json"
          folder: Traefik
          reporters: cli
          delayRequest: 5000
  build-webgo-validator:
    name: Check that Souin build as Webgo middleware
    runs-on: ubuntu-latest
    steps:
      -
        name: Add domain.com host to /etc/hosts
        run: |
          sudo echo "127.0.0.1 domain.com" | sudo tee -a /etc/hosts
      -
        name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Build Souin as Webgo plugin
        run: make build-and-run-webgo
      -
        name: Wait for Souin is really loaded inside Webgo as middleware
        uses: jakejarvis/wait-action@master
        with:
          time: 30s
      -
        name: Set Webgo logs configuration result as environment variable
        run: cd plugins/webgo/examples && echo "WEBGO_MIDDLEWARE_RESULT=$(docker-compose logs webgo | grep Souin)" >> $GITHUB_ENV
      -
        name: Check if the configuration is loaded to define if Souin is loaded too
        uses: nick-invision/assert-action@v1
        with:
          expected: '"message":"Souin configuration is now loaded."'
          actual: ${{ env.WEBGO_MIDDLEWARE_RESULT }}
          comparison: contains
      -
        name: Run Webgo E2E tests
        uses: anthonyvscode/newman-action@v1
        with:
          collection: "docs/e2e/Souin E2E.postman_collection.json"
          folder: Webgo
          reporters: cli
          delayRequest: 5000
